"""processing_and_analytics_models

Revision ID: 58afb0942c19
Revises: 002
Create Date: 2026-07-27 00:16:50.859154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58afb0942c19'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('analytics_type', sa.String(length=100), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_history_id'), ['id'], unique=False)

    op.create_table('analytics_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('analytics_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_jobs_id'), ['id'], unique=False)

    op.create_table('analytics_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_category', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=True),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metrics_metric_category'), ['metric_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_metrics_metric_name'), ['metric_name'], unique=False)

    op.create_table('customer_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('segment_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_segments_id'), ['id'], unique=False)

    op.create_table('dataset_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('numeric_columns', sa.Integer(), nullable=True),
    sa.Column('categorical_columns', sa.Integer(), nullable=True),
    sa.Column('boolean_columns', sa.Integer(), nullable=True),
    sa.Column('datetime_columns', sa.Integer(), nullable=True),
    sa.Column('text_columns', sa.Integer(), nullable=True),
    sa.Column('memory_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('null_cells', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('duplicate_columns', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    with op.batch_alter_table('dataset_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_statistics_id'), ['id'], unique=False)

    op.create_table('kpi_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_category', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_results_kpi_category'), ['kpi_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_results_kpi_name'), ['kpi_name'], unique=False)

    op.create_table('processing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_history_id'), ['id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('processing_version', sa.String(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_id'), ['id'], unique=False)

    op.create_table('transformation_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transformation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transformation_plans_id'), ['id'], unique=False)

    op.create_table('column_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('min_val', sa.Float(), nullable=True),
    sa.Column('max_val', sa.Float(), nullable=True),
    sa.Column('range_val', sa.Float(), nullable=True),
    sa.Column('q1', sa.Float(), nullable=True),
    sa.Column('q3', sa.Float(), nullable=True),
    sa.Column('iqr', sa.Float(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('missing_percentage', sa.Float(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.Column('unique_percentage', sa.Float(), nullable=True),
    sa.Column('duplicate_percentage', sa.Float(), nullable=True),
    sa.Column('outlier_count', sa.Integer(), nullable=True),
    sa.Column('outlier_percentage', sa.Float(), nullable=True),
    sa.Column('skewness', sa.Float(), nullable=True),
    sa.Column('kurtosis', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('semantic_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['dataset_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('column_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_statistics_id'), ['id'], unique=False)

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('dataset_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.alter_column('dataset_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('column_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_statistics_id'))

    op.drop_table('column_statistics')
    with op.batch_alter_table('transformation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transformation_plans_id'))

    op.drop_table('transformation_plans')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_history_id'))

    op.drop_table('processing_history')
    with op.batch_alter_table('kpi_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_results_kpi_name'))
        batch_op.drop_index(batch_op.f('ix_kpi_results_kpi_category'))
        batch_op.drop_index(batch_op.f('ix_kpi_results_id'))

    op.drop_table('kpi_results')
    with op.batch_alter_table('dataset_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_statistics_id'))

    op.drop_table('dataset_statistics')
    with op.batch_alter_table('customer_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_segments_id'))

    op.drop_table('customer_segments')
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_metrics_metric_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_metrics_metric_category'))
        batch_op.drop_index(batch_op.f('ix_analytics_metrics_id'))

    op.drop_table('analytics_metrics')
    with op.batch_alter_table('analytics_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_jobs_id'))

    op.drop_table('analytics_jobs')
    with op.batch_alter_table('analytics_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_history_id'))

    op.drop_table('analytics_history')
    # ### end Alembic commands ###
