"""Add AI Models

Revision ID: de49f3865b9d
Revises: 58afb0942c19
Create Date: 2026-08-01 23:24:35.842365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de49f3865b9d'
down_revision: Union[str, None] = '58afb0942c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='aiconversationstatus'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('REVENUE', 'CUSTOMER', 'PRODUCT', 'TREND', 'ANOMALY', 'DATA_QUALITY', 'GENERAL', name='insightcategory'), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='importancelevel'), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_id'), ['id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='importancelevel'), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACCEPTED', 'REJECTED', 'IMPLEMENTED', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_id'), ['id'], unique=False)

    op.create_table('ai_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=256), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audits_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audits_id'), ['id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('ai_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audits_id'))
        batch_op.drop_index(batch_op.f('ix_ai_audits_conversation_id'))

    op.drop_table('ai_audits')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_dataset_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insights_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_dataset_id'))

    op.drop_table('ai_insights')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_dataset_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
