import uuid
from typing import List
from sqlalchemy.orm import Session
from app.models.ai import AIInsight
from app.models.enums import InsightCategory, ImportanceLevel

class InsightExtractor:
    """Extracts and persists structured insights generated by the LLM."""
    
    def __init__(self, db: Session):
        self.db = db
        
    def store_insights(self, dataset_id: uuid.UUID, insights: List[dict], source: str) -> List[AIInsight]:
        saved_insights = []
        for ind in insights:
            # Map enum strings robustly
            try:
                category = InsightCategory(ind.get("category", "GENERAL").upper())
            except ValueError:
                category = InsightCategory.GENERAL
                
            try:
                importance = ImportanceLevel(ind.get("importance", "MEDIUM").upper())
            except ValueError:
                importance = ImportanceLevel.MEDIUM
                
            db_insight = AIInsight(
                dataset_id=dataset_id,
                category=category,
                insight=ind.get("insight", ""),
                confidence=float(ind.get("confidence", 0.0)),
                importance=importance,
                source=source
            )
            self.db.add(db_insight)
            saved_insights.append(db_insight)
        self.db.commit()
        return saved_insights
